[package]
name = "rubato"
version = "0.9.0"
authors = ["HEnquist <henrik.enquist@gmail.com>"]
description = "Asynchronous resampling library intended for audio data"
license = "MIT"
repository = "https://github.com/HEnquist/rubato"
keywords = ["interpolation", "resampling"]
categories = ["multimedia::audio"]
readme = "README.md"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["avx"]
avx = []
neon = []

[dependencies]
log = "0.4.14"
realfft = "2.0.0"
num-complex = "0.4"
num-integer = "0.1.44"
num-traits = "0.2"
audio = { git = "https://github.com/udoprog/audio", branch = "main" }
audio-core = { git = "https://github.com/udoprog/audio", branch = "main" }
bittle = "0.2.1"

[dev-dependencies] 
env_logger = "0.9.0"
criterion = "0.3.5"
rand = "0.8.4"
num-traits = "0.2.14"

[[bench]]
name = "resamplers"
harness = false

[lib]
bench = false
